### PR TITLE
Document some natives

### PR DESCRIPTION
**Pull request by PichotM**
https://github.com/alloc8or/rdr3-nativedb-data/commit/69ca41ffe4a859e95a088b1830c475b9b84ab4e6 - WATER: document world water type natives

https://github.com/alloc8or/rdr3-nativedb-data/commit/b77daf0fcd74b0c184ffa9513ec33b7188b5d2df - PED: document weird metaped outfit request natives

### CODE REVIEW

**Comment by PichotM** [comment]
Fixed!

**Comment by bugproof** [comment]
How do you find native names?? I know in the past jenkins hash was used for 32bit R* games and people made tools to bruteforce the names and later that was changed to random int64_t id. I thought the names are stored somewhere in memory... There are so many unnamed natives though, do you debug the game to find what they do? Bruteforcing seems impossible with random values. Also you seem to know the parameter names... were those names stored in memory or you named them yourself?

image

**Comment by PichotM** [comment]
> How do you find native names?? I know in the past jenkins hash was used for 32bit R* games and people made tools to bruteforce the original names and later that was changed to random int64_t id(still kinda hard to believe it is random.. ). I thought the names are stored somewhere in memory... There are so many unnamed natives though, do you debug the game to find what they do? Bruteforcing seems impossible with random values. Also you seem to know the parameter names... were those names stored in memory and reversed somehow or you named them yourself after debugging/analysis?
> 
> image
> 
> I'm pretty new to RAGE internals, I know people at openiv work at *.RPF browser for rdr2, do you think original names are stored somewhere in script files? https://openiv.com/?p=1635

These are guessed
And currently for RDR3 most named natives were either GTA V's natives or the name was in the exe

**Comment by bugproof** [comment]
How can you guess without learning what it does? So I suppose you take GTA V native sig and signature scan RDR2 to find it here, still there are natives unique to rdr. I'm curious if the original names are completely gone in the release and replaced with these random numbers or they're stored somewhere.. I think they could remove the names completely during compilation as a form of obfuscation.

**Pull request merged**
