### PR TITLE
ENTITY: document SET_ENTITY_HEADING_AND_COORDS

### PR DESCRIPTION
**Pull request by PichotM**
Credit to Snow

### CODE REVIEW

**Comment by alloc8or** [comment]
I think you mistakenly swapped "coords" and "heading".
Both 0x203BEFFDBE12E96A and 0x0918E3565C20F03C begin with ``SET_ENTITY_COORDS_`` and also set the heading.

**Comment by PichotM** [comment]
I thought your list was in order and both are between `SET_ENTITY_HEADING` `_SET_ENTITY_HEALTH`

**Comment by alloc8or** [comment]
Well yeah, it is in registration order. Their alphabetical order is different though.

**Comment by PichotM** [comment]
Fixed.

**Pull request merged**
