### PR TITLE
MAP: _BLIP_SET_MODIFIER_2

### PR DESCRIPTION
**Pull request by MRV6**

### CODE REVIEW

**Comment by alloc8or** [comment]
"Does the same" is not entirely true. By looking the disassembly it seems that this one removes any existing modifiers before setting the new one. It might also remove the modifier if you're trying to set the modifier to the same hash a second time.

**Comment by MRV6** [comment]
Ah, interesting, I didn't know that. So, "does almost the same" would be better than "does the same" then ? If you have a right suggestion let me know, i'm bad for these things.

**Comment by alloc8or** [comment]
My suggestion would be something like "Similar to _BLIP_SET_MODIFIER (0x662D364ABF16DE2F) but removes any existing modifiers before applying the new one."

**Comment by MRV6** [comment]
Great, i'll change that.

**Comment by MRV6** [comment]
Done

**Pull request merged**
